# Generated by Django 4.1.3 on 2022-12-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.DeleteModel(
            name='IncomeStream',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
