# Generated by Django 4.1.3 on 2022-12-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
