# Generated by Django 5.1 on 2025-03-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(default='XOF', max_length=255),
        ),
    ]
